### ISSUE TITLE
Trying to install your patches on a clean version of elementary OS on Acer C910.

### ISSUE THREAD

**Issue by Baparnoud** [Distroshare/distroshare-ubuntu-updater#1]
Hi Hugegreenbug,

I'm running Elementary OS on an Acer C910 using johnlewis' rom in the legacy slot. I tried to install your build of Elementary OS, but it gave me some huge graphical errors that made it impossible to install. The clean version of Elementary OS gave me the same graphical errors (albeit to a lesser extent), but they were fixed by installing a more recent kernel. I do want to use your patches tough. I installed distroshare-ubuntu-updater, but it gives me the following error:

```
jan@jan-Auron-Yuna:~/Downloads$ sudo distroshare-updater
Traceback (most recent call last):
  File "/usr/sbin/distroshare-updater", line 114, in <module>
    if __name__ == "__main__": main()
  File "/usr/sbin/distroshare-updater", line 48, in main
    repos.update_repos()
  File "build/bdist.linux-x86_64/egg/distroshare_updater/updates.py", line 42, in update_repos
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Do you have any idea how I could fix this? Or how I could install your broadwell patches manually?

Kind Regards, 

Jan

**Comment by hugegreenbug** [comment]
Jan,

I recently put some articles together to explain how I am making the
distros: https://www.distroshare.com/wiki/ . You probably can skip step 1
since you have already installed the clean version.

I haven't updated the broadwell patches in a while and I've never got the
updater set up with them. I will have to work on that soon.

Hugh

**Comment by Baparnoud** [comment]
This is exactly what I needed, thanks so much!
